name: workspace-dev

services:
  rustfs:
    image: rustfs/rustfs
    container_name: rustfs
    ports:
      - "9000:9000" 
      - "9001:9001" 
    environment:
      RUSTFS_ACCESS_KEY: ACCESS
      RUSTFS_SECRET_KEY: SECRET

    volumes:
      - ./docker_volumes/rustfs/data:/data
      - ./docker_volumes/rustfs/logs:/logs
    user: "1000:1000"
    restart: unless-stopped
    networks:
      - workspace-network

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    command: >
      redis-server
      --appendonly yes
      --save 60 1
      --loglevel warning
    volumes:
      - ./docker_volumes/redis:/data
    restart: unless-stopped
    networks:
      - workspace-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./docker_volumes/mongodb:/data/db
      - ./script/mongodb/init:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    networks:
      - workspace-network
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "mongodb://localhost:27017/admin", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 10

  dev:
    image: mcr.microsoft.com/devcontainers/universal:latest
    container_name: workspace-devcontainer
    working_dir: /workspaces/app
    volumes:
      - ..:/workspaces/app:cached
      - pnpm-store:/home/vscode/.pnpm-store
    command: sleep infinity
    networks:
      - workspace-network
    depends_on:
      - redis
      - mongodb
      - rustfs

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: always
    ports:
      - 9999:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - workspace-network
  
volumes:
  pnpm-store:

networks:
  workspace-network:
    driver: bridge
